### ISSUE TITLE
Offcentered

### ISSUE THREAD

**Issue by PaulWoitaschek** [alexjlockwood/material-pause-play-animation#3]
When setting the drawable as an icon on an imagedrawable, its totally offcentered (by maybe a centimeter). How to fix that?

And what I dont get is how to reverse the animation? It alwys just goes to from play to pause but as it hits pause it just flashes back to play.

**Comment by garretyoder** [comment]
How are you calling the transition from play/pause? If you want it offcentered, wrap it inside another view or layout and use gravity to move it.

**Comment by PaulWoitaschek** [comment]
I don' use this directly any more. I was using it in a FAB. If you set any else drawable, it is always centered.
My fix was to translate the whole canvas by `(bounds.left, bounds.top)`.
